services:
    person.repository:
        class: Infrastructure\Persistence\Doctrine\PersonRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
          - Domain\Model\Person\Person

    shiporder.repository:
            class: Infrastructure\Persistence\Doctrine\ShiporderRepository
            factory: ['@doctrine.orm.default_entity_manager', getRepository]
            arguments:
              - Domain\Model\Shiporder\Shiporder